In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('car_fuel_efficiency_2026.csv')

In [4]:
data.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
data['fuel_efficiency_mpg'].head

<bound method NDFrame.head of 0       31.9
1       31.3
2       27.5
3       28.5
4       31.0
        ...
9995    27.4
9996    30.0
9997    28.1
9998    32.2
9999    30.2
Name: fuel_efficiency_mpg, Length: 10000, dtype: float64>

In [5]:
df = data[['engine_displacement','horsepower','vehicle_weight','model_year','fuel_efficiency_mpg']]
df

,engine_displacement,horsepower,vehicle_weight,model_year,fuel_efficiency_mpg
0,2180,243.0,3870,2006,31.9
1,2390,272.0,4210,2008,31.3
2,2320,267.0,4240,1996,27.5
3,2130,258.0,4490,1989,28.5
4,2580,304.0,4510,1994,31.0
...,...,...,...,...,...
9995,2470,271.0,4690,2005,27.4
9996,2300,244.0,4370,1993,30.0
9997,2480,267.0,4590,2014,28.1
9998,2180,270.0,4450,2004,32.2
9999,2380,295.0,4370,2011,30.2

In [6]:
df.isnull().sum()

engine_displacement      0
horsepower             877
vehicle_weight           0
model_year               0
fuel_efficiency_mpg      0
dtype: int64

In [7]:
df['horsepower'].median()

np.float64(254.0)

In [8]:
def funct(n, df, ran):
    np.random.seed(ran)
    idx = np.arange(n)
    np.random.shuffle(idx)
    
    
    df_train = df.iloc[idx[:n_train]]
    df_val = df.iloc[idx[n_train:n_train+n_val]]
    df_test = df.iloc[idx[n_train+n_val:]]
    
    df_train_0 = df_train.fillna(0)
    df_val_0 = df_val.fillna(0)
    df_test_0 = df_test.fillna(0)

    y_train = np.array(df_train.fuel_efficiency_mpg.values)
    y_val = np.array(df_val.fuel_efficiency_mpg.values)
    y_test = np.array(df_test.fuel_efficiency_mpg.values)
    
    X_train_0 = df_train_0.drop(labels = 'fuel_efficiency_mpg', axis=1)
    X_val_0 = df_val_0.drop(labels = 'fuel_efficiency_mpg', axis=1)
    X_test_0 = df_test_0.drop(labels = 'fuel_efficiency_mpg', axis=1)

    w0, w = train_linear_regression(X_train_0, y_train)
    y_pred_0 = w0 + X_val_0.dot(w)

    return rmse(y_val, y_pred_0)

In [9]:
n = len(df)
n_val = int(n*0.2)
n_test = int(n*0.2)
n_train = n-n_val-n_test

np.random.seed(42)
idx = np.arange(n)
np.random.shuffle(idx)


df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train+n_val]]
df_test = df.iloc[idx[n_train+n_val:]]

df_train_0 = df_train.fillna(0)
df_val_0 = df_val.fillna(0)
df_test_0 = df_test.fillna(0)

mean = df_train['horsepower'].mean()

df_train_m = df_train.fillna(mean)
df_val_m = df_val.fillna(mean)
df_test_m = df_test.fillna(mean)

In [10]:
y_train = np.array(df_train.fuel_efficiency_mpg.values)
y_val = np.array(df_val.fuel_efficiency_mpg.values)
y_test = np.array(df_test.fuel_efficiency_mpg.values)

In [11]:
X_train_0 = df_train_0.drop(labels = 'fuel_efficiency_mpg', axis=1)
X_val_0 = df_val_0.drop(labels = 'fuel_efficiency_mpg', axis=1)
X_test_0 = df_test_0.drop(labels = 'fuel_efficiency_mpg', axis=1)

X_train_m = df_train_m.drop(labels = 'fuel_efficiency_mpg', axis=1)
X_val_m = df_val_m.drop(labels = 'fuel_efficiency_mpg', axis=1)
X_test_m = df_test_m.drop(labels = 'fuel_efficiency_mpg', axis=1)

In [12]:
y_train

array([32.5, 29.1, 34.1, ..., 27.7, 31.6, 28. ], shape=(6000,))

In [13]:
X_train_0

      engine_displacement  horsepower  vehicle_weight  model_year
6252                 1900       239.0            3790        2015
4684                 2000       224.0            4380        1992
1731                 2330       286.0            4090        2022
4742                 2300         0.0            4150        1997
4521                 2340       269.0            4400        2001
...                   ...         ...             ...         ...
7895                 2280       242.0            4590        2018
9590                 2300         0.0            4240        1984
7288                 2240       255.0            4190        1989
278                  2430       254.0            4280        2020
3252                 2390       266.0            4220        1996

[6000 rows x 4 columns]

In [14]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)
    
    return w_full[0], w_full[1:]

In [15]:
w0, w = train_linear_regression(X_train_0, y_train)
y_pred_0 = w0 + X_val_0.dot(w)

In [16]:
w0, w = train_linear_regression(X_train_m, y_train)
y_pred_m = w0 + X_val_m.dot(w)

In [17]:
def rmse(y, y_pred):
    se = (y - y_pred) ** 2
    mse = se.mean()
    return np.sqrt(mse)

In [18]:
round(rmse(y_val, y_pred_0),3)

np.float64(2.205)

In [19]:
round(rmse(y_val, y_pred_m), 3)

np.float64(2.202)

In [20]:
r = [0, 0.01, 0.1, 1, 5, 10, 100]

In [67]:
def train_linear_regression_reg(X, y, r=0.001):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX = XTX + r * np.eye(XTX.shape[0])

    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)
    
    return w_full[0], w_full[1:]

In [22]:
for reg in r:
    w0, w = train_linear_regression_reg(X_train_0, y_train, reg)
    y_pred = w0 + X_val_0.dot(w)
    print (reg, round(rmse(y_val, y_pred),4))

0 2.2053
0.01 2.2058
0.1 2.2241
1 2.3492
5 2.4094
10 2.4195
100 2.4292

In [28]:
n = len(df)
n_val = int(n*0.2)
n_test = int(n*0.2)
n_train = n-n_val-n_test
arr = []
for ran_seed in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]:
    arr.append(funct(n, df, ran_seed))
std = round(np.std(arr), 3)
std

np.float64(0.029)

In [46]:
np.random.seed(9)
idx = np.arange(n)
np.random.shuffle(idx)


df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train+n_val]]
df_test = df.iloc[idx[n_train+n_val:]]

df_train_0 = df_train.fillna(0)
df_val_0 = df_val.fillna(0)
df_test_0 = df_test.fillna(0)

In [73]:
df_full_train = pd.concat([df_train_0, df_val_0])
df_full_train

,engine_displacement,horsepower,vehicle_weight,model_year,fuel_efficiency_mpg
3644,2320,246.0,4100,2014,32.5
9184,2230,252.0,4250,1998,33.2
520,2700,276.0,4490,2008,32.4
5685,2220,269.0,4060,2004,29.9
2401,2370,0.0,4690,1979,26.4
...,...,...,...,...,...
8981,2690,324.0,4510,2023,35.7
3978,1920,190.0,4000,1998,30.8
6198,1800,225.0,3980,1994,29.1
1102,1970,232.0,3560,2009,32.2
65,2180,254.0,3970,2018,35.6

In [74]:
y_train = np.array(df_full_train.fuel_efficiency_mpg.values)
y_test = np.array(df_test.fuel_efficiency_mpg.values)

In [75]:
X_train_0 = df_full_train.drop(labels = 'fuel_efficiency_mpg', axis=1)
X_test_0 = df_test_0.drop(labels = 'fuel_efficiency_mpg', axis=1)

In [78]:
w0, w = train_linear_regression_reg(X_train_0, y_train, 0.001)
y_pred = w0 + X_test_0.dot(w)
w0

np.float64(-152.37535772493302)

In [79]:
rmse(y_test, y_pred)

np.float64(2.2358277471917636)